[package]
name = "chat-client"
version = "0.1.0"
edition = "2021"

[dependencies]
chatlib = { package = "chat-lib", path = "../chat-lib" }
serde = {  version = "1.0.192", features = ["derive"] }
image = "0.24.7"
fastrand = "2.0.1"
envy = "0.4.2"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
